[project]
name = "ytdlp-rest-api"
version = "0.1.0"
description = "Send URL, get the video back."
readme = "README.md"
authors = [
    { name = "Electronic Mango", email = "78230210+Electronic-Mango@users.noreply.github.com" },
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.3",
    "yt-dlp[default]>=2026.8.19",
]

[dependency-groups]
dev = ["ruff>=0.16.7"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A002",   # "format" shadows a builtin, but it also exactly matches yt-dlp parameter
    "COM812", # Avoid issues with formatter
    "CPY001", # Copyright notice isn't necessary here
    "D1",     # Ignore all missing docstring rules
    "D203",   # Conflicts with D211
    "D212",   # Conflicts with D213
    "TC003",  # Just unnecessary
]
